ID="id"
NAME="Enrique"
IP="localhost:8000"
STATUS="Status"
SERVERIP="localhost:80"
DESCRIPTION="A_text_is_any_object_that_can_be_read,_including:_Documents:_Religious_text,_a_writing_that_a_religious_tradition_considers_to_be_sacred"
curl "$SERVERIP"/device/new/"$NAME/$STATUS/$IP"
